name: Github Packages

on:
  push:
    branches: [ master ]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Unit tests
        run: bash ./gradlew :contentview:test --stacktrace

  publish:
    name: Publish library
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: repo-sync
        uses: repo-sync/github-sync@v2
        with:
          source_branch: "version-tag"
          destination_branch: "master"
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build library
        run: bash ./gradlew incrementVersion :contentview:build --stacktrace

      - name: Publish library
        run: bash ./gradlew publish --stacktrace
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER: anacoimbrag

      - name: Update git
        run: git checkout version-tag && git commit -a -m "update version" && git push origin version-tag

      - name: Upload aar
        uses: actions/upload-artifact@v1
        with:
          name: lib
          path: ${{ github.workspace }}/**/*.aar
