name: Github Packages

on:
  push:
    branches: [ master ]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Unit tests
        run: bash ./gradlew :contentview:codeCoverageReport --stacktrace

      - name: Coverage Report
        uses: codecov/codecov-action@v1
        with:
          file: ./contentview/build/reports/jacoco/codeCoverageReport/codeCoverageReport.xml # optional

  publish:
    name: Publish library
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Update version
        run: git fetch --tags && echo version=$(git tag | tail -1) > version.properties

      - name: Build library
        run: bash ./gradlew incrementVersion contentview:assembleRelease --stacktrace

      - name: Upload aar
        uses: actions/upload-artifact@v1
        with:
          name: lib
          path: contentview/build/outputs/aar/contentview-release.aar
